export const SPECIFICATION_GET_BY_SPACE_ID = 'SPECIFICATION_GET_BY_SPACE_ID'
export const SPECIFICATION_SAVING = 'SPECIFICATION_SAVING'
export const SPECIFICATION_SAVED = 'SPECIFICATION_SAVED'
export const SPECIFICATION_GET_FAILURE = 'SPECIFICATION_GET_FAILURE'